services:
  resource-db:
    image: postgres:17-alpine3.21
    container_name: resource-db
    environment:
      POSTGRES_USER: ${RESOURCE_DB_USERNAME}
      POSTGRES_PASSWORD: ${RESOURCE_DB_PASSWORD}
      POSTGRES_DB: resource-db
    volumes:
      - ./init-scripts/resource-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  song-db:
    image: postgres:17-alpine3.21
    container_name: song-db
    environment:
      POSTGRES_USER: ${SONG_DB_USERNAME}
      POSTGRES_PASSWORD: ${SONG_DB_PASSWORD}
      POSTGRES_DB: song-db
    volumes:
      - ./init-scripts/song-db:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"

  resource-service:
    container_name: resource-service
    build:
      context: ./resource-service
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: ${RESOURCE_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${RESOURCE_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${RESOURCE_DB_PASSWORD}
      EUREKA_REGISTRATION_URL: ${EUREKA_REGISTRATION_URL}
      RESOURCE_S3_URL: ${RESOURCE_S3_URL}
      RESOURCE_S3_REGION: ${RESOURCE_S3_REGION}
      RESOURCE_S3_ACCESS_KEY_ID: ${RESOURCE_S3_ACCESS_KEY_ID}
      RESOURCE_S3_SECRET_ACCESS_KEY: ${RESOURCE_S3_SECRET_ACCESS_KEY}
      RESOURCE_S3_BUCKET_NAME: ${RESOURCE_S3_BUCKET_NAME}
    ports:
      - "8081:8081"
    depends_on:
      - resource-db
      - service-registry
      - localstack

  song-service:
    build:
      context: ./song-service
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: ${SONG_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${SONG_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SONG_DB_PASSWORD}
      EUREKA_REGISTRATION_URL: ${EUREKA_REGISTRATION_URL}
    ports:
      - "8082:8082"
    depends_on:
    - song-db
    - service-registry

  resource-processor:
    build:
      context: ./resource-processor
      dockerfile: Dockerfile
    ports:
      - "8083:8083"

  service-registry:
    container_name: service-registry
    build:
      context: ./service-registry
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  localstack:
    image: localstack/localstack
    ports:
      - 4510-4559:4510-4559
      - 4566:4566
    environment:
      - SERVICES=s3
      - DEBUG=1
      - HOSTNAME=localstack
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - ./init-scripts/localstack/localstack-ready.sh:/etc/localstack/init/ready.d/localstack-ready.sh