global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'eureka'
    eureka_sd_configs:
      - server: http://service-registry:8761/eureka

    relabel_configs:
      - source_labels: [__meta_eureka_app_instance_metadata_prometheus_scrape]
        action: keep
        regex: true

      - source_labels: [__meta_eureka_app_instance_metadata_prometheus_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)

      - source_labels: [__address__, __meta_eureka_app_instance_metadata_prometheus_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__

  - job_name: 'tempo'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['tempo:3200']

  - job_name: 'loki'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'loki:3100' ]