spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=Cookie
      routes:
        - id: song-service-root
          uri: lb://SONG-SERVICE
          predicates:
            - Path=/songs
            - Method=POST
          filters:
            - name: JwtAuthentication
              args:
                allowAnonymous: false
                roles:
                  - ADMIN
            - name: CircuitBreaker
              args:
                name: gatewayCircuitBreaker
                fallbackUri: forward:/fallback/songs
                statusCodes:
                  - BAD_GATEWAY
                  - SERVICE_UNAVAILABLE
                  - GATEWAY_TIMEOUT
                  - TOO_MANY_REQUESTS
                excludeStatusCodes:
                  - UNAUTHORIZED
                  - FORBIDDEN


        - id: song-service
          uri: lb://SONG-SERVICE
          predicates:
            - Path=/songs/**
            - Method=GET
          filters:
            - name: JwtAuthentication
              args:
                allowAnonymous: false
                roles:
                  - USER
            - name: CircuitBreaker
              args:
                name: gatewayCircuitBreaker
                fallbackUri: forward:/fallback/songs
                statusCodes:
                  - BAD_GATEWAY
                  - SERVICE_UNAVAILABLE
                  - GATEWAY_TIMEOUT
                  - TOO_MANY_REQUESTS
                excludeStatusCodes:
                  - UNAUTHORIZED
                  - FORBIDDEN


        - id: song-service-delete
          uri: lb://SONG-SERVICE
          predicates:
            - Path=/songs
            - Method=DELETE
            - Query=id
          filters:
            - name: JwtAuthentication
              args:
                allowAnonymous: false
                roles:
                  - ADMIN
            - name: CircuitBreaker
              args:
                name: gatewayCircuitBreaker
                fallbackUri: forward:/fallback/songs
                statusCodes:
                  - BAD_GATEWAY
                  - SERVICE_UNAVAILABLE
                  - GATEWAY_TIMEOUT
                  - TOO_MANY_REQUESTS
                excludeStatusCodes:
                  - UNAUTHORIZED
                  - FORBIDDEN


        - id: resource-service-root
          uri: lb://RESOURCE-SERVICE
          predicates:
            - Path=/resources
            - Method=POST
          filters:
            - name: JwtAuthentication
              args:
                allowAnonymous: false
                roles:
                   - ADMIN
            - name: CircuitBreaker
              args:
                name: gatewayCircuitBreaker
                fallbackUri: forward:/fallback/resources
                statusCodes:
                  - BAD_GATEWAY
                  - SERVICE_UNAVAILABLE
                  - GATEWAY_TIMEOUT
                  - TOO_MANY_REQUESTS
                excludeStatusCodes:
                  - UNAUTHORIZED
                  - FORBIDDEN


        - id: resource-service
          uri: lb://RESOURCE-SERVICE
          predicates:
            - Path=/resources/**
            - Method=GET
          filters:
            - name: JwtAuthentication
              args:
                allowAnonymous: false
                roles:
                  - USER
            - name: CircuitBreaker
              args:
                name: gatewayCircuitBreaker
                fallbackUri: forward:/fallback/resources
                statusCodes:
                  - BAD_GATEWAY
                  - SERVICE_UNAVAILABLE
                  - GATEWAY_TIMEOUT
                  - TOO_MANY_REQUESTS
                excludeStatusCodes:
                  - UNAUTHORIZED
                  - FORBIDDEN


        - id: resource-service-delete
          uri: lb://RESOURCE-SERVICE
          predicates:
            - Path=/resources
            - Method=DELETE
            - Query=id
          filters:
            - name: JwtAuthentication
              args:
                allowAnonymous: false
                roles:
                  - ADMIN
            - name: CircuitBreaker
              args:
                name: gatewayCircuitBreaker
                fallbackUri: forward:/fallback/resources
                statusCodes:
                  - BAD_GATEWAY
                  - SERVICE_UNAVAILABLE
                  - GATEWAY_TIMEOUT
                  - TOO_MANY_REQUESTS
                excludeStatusCodes:
                  - UNAUTHORIZED
                  - FORBIDDEN


        - id: storage-service-root-post
          uri: lb://STORAGE-SERVICE
          predicates:
            - Path=/storages
            - Method=POST
          filters:
            - name: JwtAuthentication
              args:
                allowAnonymous: false
                roles:
                  - ADMIN
            - name: CircuitBreaker
              args:
                name: gatewayCircuitBreaker
                fallbackUri: forward:/fallback/storages
                statusCodes:
                  - BAD_GATEWAY
                  - SERVICE_UNAVAILABLE
                  - GATEWAY_TIMEOUT
                  - TOO_MANY_REQUESTS
                excludeStatusCodes:
                  - UNAUTHORIZED
                  - FORBIDDEN


        - id: storage-service-root-get
          uri: lb://STORAGE-SERVICE
          predicates:
            - Path=/storages
            - Method=GET
          filters:
            - name: JwtAuthentication
              args:
                allowAnonymous: false
                roles:
                  - USER
            - name: CircuitBreaker
              args:
                name: gatewayCircuitBreaker
                fallbackUri: forward:/fallback/storages
                statusCodes:
                  - BAD_GATEWAY
                  - SERVICE_UNAVAILABLE
                  - GATEWAY_TIMEOUT
                  - TOO_MANY_REQUESTS
                excludeStatusCodes:
                  - UNAUTHORIZED
                  - FORBIDDEN


        - id: storage-service-delete
          uri: lb://STORAGE-SERVICE
          predicates:
            - Path=/storages
            - Method=DELETE
            - Query=id
          filters:
            - name: JwtAuthentication
              args:
                allowAnonymous: false
                roles:
                  - ADMIN
            - name: CircuitBreaker
              args:
                name: gatewayCircuitBreaker
                fallbackUri: forward:/fallback/storages
                statusCodes:
                  - BAD_GATEWAY
                  - SERVICE_UNAVAILABLE
                  - GATEWAY_TIMEOUT
                  - TOO_MANY_REQUESTS
                excludeStatusCodes:
                  - UNAUTHORIZED
                  - FORBIDDEN


        - id: auth-service-get-token
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/oauth2/token
            - Method=POST
          filters:
            - name: JwtAuthentication
              args:
                allowAnonymous: true
            - name: CircuitBreaker
              args:
                name: gatewayCircuitBreaker
                fallbackUri: forward:/fallback/auth
                statusCodes:
                  - BAD_GATEWAY
                  - SERVICE_UNAVAILABLE
                  - GATEWAY_TIMEOUT
                  - TOO_MANY_REQUESTS
                excludeStatusCodes:
                  - UNAUTHORIZED
                  - FORBIDDEN



resilience4j:
  circuitbreaker:
    instances:
      exampleCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true