spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: song-service-root
          uri: lb://SONG-SERVICE
          predicates:
            - Path=/songs
            - Method=POST
          filters:
            - name: CircuitBreaker
              args:
                name: gatewayCircuitBreaker
                fallbackUri: forward:/fallback/songs

        - id: song-service
          uri: lb://SONG-SERVICE
          predicates:
            - Path=/songs/**
          filters:
            - name: CircuitBreaker
              args:
                name: gatewayCircuitBreaker
                fallbackUri: forward:/fallback/songs

        - id: song-service-delete
          uri: lb://SONG-SERVICE
          predicates:
            - Path=/songs
            - Method=DELETE
            - Query=id
          filters:
            - name: CircuitBreaker
              args:
                name: gatewayCircuitBreaker
                fallbackUri: forward:/fallback/songs

        - id: resource-service-root
          uri: lb://RESOURCE-SERVICE
          predicates:
            - Path=/resources
            - Method=POST
          filters:
            - name: CircuitBreaker
              args:
                name: gatewayCircuitBreaker
                fallbackUri: forward:/fallback/resources

        - id: resource-service
          uri: lb://RESOURCE-SERVICE
          predicates:
            - Path=/resources/**
            - Method=GET
          filters:
            - name: CircuitBreaker
              args:
                name: gatewayCircuitBreaker
                fallbackUri: forward:/fallback/resources

        - id: resource-service-delete
          uri: lb://RESOURCE-SERVICE
          predicates:
            - Path=/resources
            - Method=DELETE
            - Query=id
          filters:
            - name: CircuitBreaker
              args:
                name: gatewayCircuitBreaker
                fallbackUri: forward:/fallback/resources


resilience4j.circuitbreaker:
  instances:
    gatewayCircuitBreaker:
      registerHealthIndicator: true
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 10s
      permittedNumberOfCallsInHalfOpenState: 3
      minimumNumberOfCalls: 5